name = "ashley-site"
compatibility_date = "2026-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "ashley-site"
database_id = "PLACEHOLDER_FILL_AFTER_CREATE"

[vars]
JWT_SECRET = "change-me-after-deploy-please-use-random-64-chars"
