async function renderVehicle(root) {
  const [vehicles, anomalies] = await Promise.all([api('/vehicle/list'), api('/vehicle/anomalies')]);
  root.innerHTML = `
    <div class="grid grid-4">${metric('车辆总数',vehicles.length,'模拟监管车辆','cyan')}${metric('在线车辆',vehicles.filter(v=>v.online).length,'实时定位在线','green')}${metric('异常车辆',anomalies.length,'需核查处置','red')}${metric('两客一危',vehicles.filter(v=>v.type==='两客一危').length,'重点营运车辆','yellow')}</div>
    <div class="grid grid-2" style="margin-top:16px"><div class="card"><h3>车型分布</h3><div id="vehiclePie" class="chart-sm"></div></div><div class="card"><h3>异常车辆</h3><div class="list">${anomalies.slice(0,6).map(a=>`<div class="item"><div class="item-title">${tag(a.plateNo,a.level)} ${a.type}</div><div class="muted">${a.companyName}｜${a.riskTags.join('、')}</div>${prda(a.prda)}</div>`).join('')}</div></div></div>
    <div class="card" style="margin-top:16px"><div class="toolbar"><select id="vehicleType" class="select"><option value="">全部类型</option><option>普通货运</option><option>两客一危</option><option>大件运输</option><option>城市客运</option></select><span class="muted">点击车牌查看企业、司机、违法线索和轨迹回放。</span></div><div id="vehicleTable"></div></div>
    <div class="card" style="margin-top:16px"><h3>车辆详情 / 轨迹回放</h3><div id="vehicleDetail" class="muted">点击表格中的车牌查看轨迹点。</div></div>`;
  const drawTable=(type='')=>{const list=type?vehicles.filter(v=>v.type===type):vehicles;document.getElementById('vehicleTable').innerHTML=table(['车牌','类型','企业','驾驶员','位置','速度','状态','风险标签'],list.map(v=>`<tr><td><a class="download" href="javascript:showVehicle('${v.id}')">${v.plateNo}</a></td><td>${v.type}</td><td>${v.companyName}</td><td>${v.driver}</td><td>${v.location}</td><td>${v.speed}</td><td>${tag(v.status,v.status==='异常'?'高':v.status==='关注'?'中':'低')}</td><td>${v.riskTags.map(t=>tag(t,'中')).join('')}</td></tr>`));};
  drawTable(); document.getElementById('vehicleType').onchange=e=>drawTable(e.target.value);
  const groups={}; vehicles.forEach(v=>groups[v.type]=(groups[v.type]||0)+1); chart('vehiclePie',{tooltip:{trigger:'item'},series:[{type:'pie',radius:'70%',data:Object.entries(groups).map(([name,value])=>({name,value}))}]});
}
async function showVehicle(id){ const v=await api(`/vehicle/${id}`); const t=await api(`/vehicle/${id}/trajectory`); const color=s=>({'正常行驶':'#00e396','停留':'#feb019','偏航':'#775dd0','超速':'#ff4560','低速拥堵':'#f6c85f','离线':'#999'}[s]||'#00d4ff'); document.getElementById('vehicleDetail').innerHTML=`<div class="grid grid-2"><div><div class="item"><div class="item-title">${v.plateNo}｜${v.type}｜${tag(v.status,v.status==='异常'?'高':'中')}</div><div>企业：${v.company?.name||v.companyName}（信用${v.company?.creditScore||'-'} / ${v.company?.riskLevel||'-'}）</div><div>司机：${v.driverInfo?.name||v.driver}（资质：${v.driverInfo?.qualification||'-'}，风险分${v.driverInfo?.riskScore||'-'}）</div><div>线索：${(v.clues||[]).map(c=>tag(c.id+':'+c.type,c.level)).join('')||'无'}</div><div class="muted">${v.creditBackground?.explanation||''}</div></div><h4>轨迹点列表</h4><div class="track-list">${t.trajectory.map(p=>`<div><b>${p.time}</b> ${tag(p.status,p.status==='超速'||p.status==='偏航'?'高':p.status==='低速拥堵'||p.status==='停留'?'中':'低')} ${p.speed}km/h ${p.roadSegmentId}</div>`).join('')}</div></div><div><div id="trajectoryChart" class="chart"></div></div></div>`; const pts=t.trajectory.map(p=>[p.lng,p.lat,p.speed,p.status,p.time]); chart('trajectoryChart',{...baseChart(),xAxis:{show:false,min:115,max:122.5},yAxis:{show:false,min:34.5,max:38},tooltip:{formatter:p=>`${p.data[4]}<br>${p.data[3]} ${p.data[2]}km/h`},series:[{type:'lines',coordinateSystem:'cartesian2d',data:[{coords:pts.map(p=>[p[0],p[1]])}],lineStyle:{color:'#00d4ff',width:3},effect:{show:true,symbol:'arrow',symbolSize:8}},{type:'scatter',coordinateSystem:'cartesian2d',data:pts,symbolSize:p=>p[3]==='停留'?12:8,itemStyle:{color:p=>color(p.data[3])}}]}); }
